# Generated by Django 4.2 on 2023-05-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_tags_products_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='notes',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
